#include<iostream>

using namespace std;

main(){
	
	int a,b,c,d,e;
	int h,i,j,k,l;
	
	cout<<"Enter the number a:";
	cin>>a;
	h=a*a*a;
	cout<<h<<endl;
	
	cout<<"Enter the number b:";
	cin>>b;
	i=b*b*b;
	cout<<i<<endl;
	
	cout<<"Enter the number c:";
	cin>>c;
	j=c*c*c;
	cout<<j<<endl;
	
	cout<<"Enter the number d:";
	cin>>d;
	k=d*d*d;
	cout<<k<<endl;
	
	cout<<"Enter the number e:";
	cin>>e;
	l=e*e*e;
	cout<<l<<endl;
	
	
	int v[5]={h,i,j,k,l};
	cout<<v[5]<<endl;
	
}
